#ifndef HEADERS_H
#define HEADERS_H

#include <iostream>
#include <iomanip>
#include <stack>
#include <vector>
#include <fstream>
#include <sstream>
#include <string>
#include <algorithm>
#include <cctype>
#include <QLabel>
#include <QDebug>
#include <cstdio>
#include <QGraphicsView>
#include <QGraphicsScene>
#include <QDragEnterEvent>
#include <QDragLeaveEvent>
#include <QDragMoveEvent>
#include <QDropEvent>
#include <QWidget>
#include <QMimeData>
#include <QGraphicsPixmapItem>
#include <QPixmap>
#include <QString>
#include <QApplication>
#include <QMessageBox>
#include <cmath>
#include <string.h>
#include <QSqlDatabase>
#include <QSqlQuery>
#include <QVariant>
#include <QTableWidget>
#include <QTableWidgetItem>
#include <QStandardItemModel>
#include <limits>
#include <QMainWindow>
#include <QLineEdit>
#include <QtSql>
#include <QFileInfo>
#include <QDialog>
#include <QTimer>
#include <QTime>
#include <QDesktopServices>
#include <QUrl>
#include <QListWidget>
#include <QFile>
#include <QTextStream>

#include "calculationfacade.h"
#include "calcfactory.h"
#include "abstractcalc.h"
#include "ownerdialog.h"
#include "mainwindow.h"
#include "ValidateInput.h"
#include "linked_list.h"
#include "boyer_moore.h"
#include "hashtable.h"
#include "abv_tree.h"
#include "registerdialog.h"
#include "portaldialog.h"
#include "unza.h"
#include "guapcalc.h"
#include "te_librarycalc.h"
#include "ted_talkscalc.h"
#include "jmax_limcalc.h"
#include "calcfactoryimpl.h"
#include "book_data.h"
#endif // HEADERS_H
